#cloud-config
packages:
  - nginx
  - python3-pip
  - unzip

runcmd:
  # Remove the default Nginx configuration
  - rm /etc/nginx/sites-available/default
  
write_files:
  - path: /etc/nginx/sites-available/default
    content: |
      server {
          listen 443 ssl default_server;
          listen [::]:443 ssl default_server;

          server_name _;

          ssl_certificate /etc/ssl/certs/akmworkshop.crt;
          ssl_certificate_key /etc/ssl/private/akmworkshop.key;
          ssl_protocols TLSv1.2 TLSv1.3;
          ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
          ssl_prefer_server_ciphers on;

          location / {
              proxy_pass http://127.0.0.1:5543;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
  
  - path: /etc/systemd/system/deepsparse.service
    content: |
      [Unit]
      Description=DeepSparse Service
      After=network.target

      [Service]
      Type=simple
      ExecStart=/bin/bash /usr/local/bin/deepsparse-service.sh
      Restart=always

      [Install]
      WantedBy=multi-user.target

runcmd:
  - wget https://slepcevic.net/cerworkshop.zip -O /tmp/cerworkshop.zip
  - unzip /tmp/cerworkshop.zip -d /tmp/cerworkshop
  - mv /tmp/cerworkshop/akmworkshop.crt /etc/ssl/certs/
  - mv /tmp/cerworkshop/akmworkshop.key /etc/ssl/private/
  - chmod 644 /etc/ssl/certs/akmworkshop.crt
  - chmod 600 /etc/ssl/private/akmworkshop.key
  - pip3 install deepsparse==1.7.0
  - pip3 install deepsparse[server]==1.7.0
  - pip3 install deepsparse[transformers]==1.7.0
  - systemctl enable nginx
  - systemctl restart nginx
  - echo "deepsparse.server --host "127.0.0.1" --task sentiment-analysis --model_path zoo:nlp/sentiment_analysis/obert-base/pytorch/huggingface/sst2/pruned90_quant-none" > /usr/local/bin/deepsparse-service.sh
  - chmod +x /usr/local/bin/deepsparse-service.sh
  - systemctl daemon-reload
  - systemctl enable deepsparse
  - systemctl start deepsparse
